package com.shopsphere.service;
import com.shopsphere.dto.AuthDtos.*; import com.shopsphere.entity.*; import com.shopsphere.exception.ApiException; import com.shopsphere.repository.*; import com.shopsphere.security.CurrentUser; import org.springframework.data.domain.*; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.util.*;
@Service public class OrderService {private final OrderRepository orders;private final OrderItemRepository orderItems;private final CartRepository carts;private final CartItemRepository cartItems;private final InventoryRepository inventory;private final AddressService addresses;private final CurrentUser current;private final CouponRepository coupons;
 public OrderService(OrderRepository o,OrderItemRepository oi,CartRepository c,CartItemRepository ci,InventoryRepository i,AddressService a,CurrentUser cu,CouponRepository cp){orders=o;orderItems=oi;carts=c;cartItems=ci;inventory=i;addresses=a;current=cu;coupons=cp;}
 @Transactional public OrderResponse create(Authentication a,CreateOrderRequest r){User u=current.get(a);Cart cart=carts.findByUser(u).orElseThrow(()->new ApiException("CART_EMPTY","Cart is empty"));var lines=cartItems.findAllByCart(cart);if(lines.isEmpty())throw new ApiException("CART_EMPTY","Cart is empty");Address addr=addresses.get(r.addressId(),a);BigDecimal subtotal=BigDecimal.ZERO;Order o=new Order();o.setUser(u);o.setShippingAddressSnapshot(addr.getLine1()+", "+addr.getCity()+", "+addr.getState()+" "+addr.getPostalCode()+", "+addr.getCountry());orders.save(o);
  for(CartItem line:lines){Inventory inv=inventory.findForUpdate(line.getProduct().getId()).orElseThrow(()->new ApiException("INVENTORY_NOT_FOUND","Inventory missing"));if(inv.getQuantity()<line.getQuantity())throw new ApiException("INSUFFICIENT_STOCK","Insufficient stock for "+line.getProduct().getName());inv.setQuantity(inv.getQuantity()-line.getQuantity());OrderItem oi=new OrderItem();oi.setOrder(o);oi.setProduct(line.getProduct());oi.setQuantity(line.getQuantity());oi.setUnitPrice(line.getProduct().getPrice());orderItems.save(oi);subtotal=subtotal.add(line.getProduct().getPrice().multiply(BigDecimal.valueOf(line.getQuantity())));}
  BigDecimal discount=BigDecimal.ZERO;if(r.couponCode()!=null&&!r.couponCode().isBlank()){Coupon cp=coupons.findByCodeIgnoreCase(r.couponCode()).orElseThrow(()->new ApiException("INVALID_COUPON","Coupon not found"));if(!cp.isActive()||(cp.getExpiresAt()!=null&&cp.getExpiresAt().isBefore(java.time.Instant.now())))throw new ApiException("INVALID_COUPON","Coupon expired or inactive");discount=subtotal.multiply(cp.getDiscountPercent()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);}
  o.setSubtotal(subtotal);o.setDiscount(discount);o.setTotal(subtotal.subtract(discount));o.setStatus(OrderStatus.CONFIRMED);cartItems.deleteAllByCart(cart);return map(o); }
 @Transactional(readOnly=true) public Page<OrderResponse> mine(Authentication a,Pageable p){return orders.findAllByUser(current.get(a),p).map(this::map);}
 @Transactional(readOnly=true) public OrderResponse get(UUID id,Authentication a){Order o=orders.findById(id).orElseThrow(()->new ApiException("ORDER_NOT_FOUND","Order not found"));if(!o.getUser().getId().equals(current.get(a).getId()))throw new ApiException("FORBIDDEN","Order does not belong to user");return map(o);}
 @Transactional public void cancel(UUID id,Authentication a){Order o=orders.findById(id).orElseThrow();if(!o.getUser().getId().equals(current.get(a).getId()))throw new ApiException("FORBIDDEN","Order does not belong to user");if(!(o.getStatus()==OrderStatus.PENDING||o.getStatus()==OrderStatus.CONFIRMED))throw new ApiException("CANNOT_CANCEL","Order cannot be cancelled now");for(OrderItem i:orderItems.findAllByOrder(o)){Inventory inv=inventory.findForUpdate(i.getProduct().getId()).orElseThrow();inv.setQuantity(inv.getQuantity()+i.getQuantity());}o.setStatus(OrderStatus.CANCELLED);}
 private OrderResponse map(Order o){var items=orderItems.findAllByOrder(o).stream().map(i->new OrderItemResponse(i.getProduct().getId(),i.getProduct().getName(),i.getQuantity(),i.getUnitPrice())).toList();return new OrderResponse(o.getId(),o.getStatus().name(),o.getSubtotal(),o.getDiscount(),o.getTotal(),o.getShippingAddressSnapshot(),items,o.getCreatedAt());}
}
